### ISSUE TITLE
Question about how to include 3DFin in CloudCompare python plugin and 3DFin error after start

### ISSUE THREAD

**Issue by Loris-L** [3DFin/3DFin#45]
I compiled CloudCompare with python plugin in my Ubuntu 22.04 LTS and then i followed the instructions to install 3DFin by pip3 with its dependencies. But in this way i didn't be able to install 3DFin as a plugin by python plugin, i got the error: "no module three_d_fin found" but it's installed, if i run "3DFin" or "python3 - m three_d_fin" in terminal, the GUI opens.
So i tried to rebuild CloudCompare with 3DFin already installed in local, and with my surprise i open CloudCompare seeing that 3DFin is already installed as a plugin. How is it possible? Can you give me an explanation?
Anyway, i started to use 3DFin to analyze a forest point cloud, but i had the same error explained in issue #42, so have i to use only the expert tab without consider the basic tab? Have i to try different parameters only in voxel resolution sections?

**Comment by rjanvier** [comment]
`pip` used by CC is the  `pip` of your current PYTHONPATH so it will give the same "results"  if you use it via the plugin or via the command line/terminal. Moreover, CC looks for plugin on the PYTHONPATH. As a result you can both install 3DFin via CC Gui or command line, it's "virtualy" the same thing so it's not clear why it was not working on the first place. For the voxel parameters, it depends on the density of your data, you have to adapt all voxels parameters to your dataset, yes.

**Comment by Loris-L** [comment]
@rjanvier thanks to reply.
I don't know why also the installation by `pip` command in terminal CloudCompare install 3DFin as plugin, but as long as it works it’s okay.
About my dataset, i've about 1 hectare of martelloscope, and the points cloud is very dense. I found and used these parameters shown in the screenshot without errors, but the results aren't accurated.

![IMG_20231023_233812_424.png](https://github.com/3DFin/3DFin/assets/117673134/c3501bd3-250e-4904-a2e0-1a60e6f9044b)

Maybe do i have to change also the other parameters?

**Comment by rjanvier** [comment]
Thanks Loris ! 
I'm sorry I'm not the forest/algoritmic expert here :).  On my side,I think your stem extraction (x,y) and (z) voxel resolution are a bit too coarse.  But it all depends on the original resolution of your point cloud.
Maybe @CaboCarlos or @Diegolainor could have wiser advices to help you to deal with your dataset.

**Comment by Loris-L** [comment]
@rjanvier thanks to you for your tip, i try to follow it and if there are others i follow them too.
For this martelloscope, it's been used GeoSLAM Zeb Horizon and the entire points cloud is very dense with high resolution.

**Comment by Diegolainor** [comment]
Hi Loris-L, I hope you are doing great. Thank you very much for starting an issue! The software is still in the early stages of formal testing, so any feedback is highly appreciated. 

I noticed that you are modifying several parameters to adapt the software to your plot: that's great, but makes it a bit harder to detect what could be going wrong. I see that you are using 0.15 `voxel resolution` at every step. Kind of obvious, but keep in mind that voxels have a volume, and that increasing the voxel size greatly increases the number of points that collapse into them. For instance, a 1 m^3 solid block would only fit roughly 300 0.15 x 0,15 x 0.15 voxels. But that is for a solid block. When the software is identifying the stems within the stripe, it is mostly looking at hollow cylinders (hopefully!). I would think that keeping a minimum of 600 voxels per possible stem might be a bit too high of a number in this case.

I would recommend either decreasing the `minimum number of points` (voxels) in that stage (50-80 sounds more fitting) of decreasing the `voxel resolution`, but keeping in mind the volumetric nature of the latter. Other parameter values seem reasonable, although that will largely depend on the point cloud. Maybe the `verticality threshold` is a bit too low as well, but I'd suggest modifying parameters one at a time. 

Please, keep us updated with your progress, and I hope you find 3DFin useful for your marteloscope!
Diego

**Comment by Loris-L** [comment]
Hi @Diegolainor, thanks for reply and tips.
I'll try what you said to me, i hope i'll found the right parameters.
The parameters extraction of this martelloscope is the base for my master thesis, and i choosed (with my supervisors) 3DFin in CC to do it. If it isn't a problem, i'll update you also or only by e-mail. Thanks again

**Comment by CaboCarlos** [comment]
Hi Loris,
As Diego said, it seems that you changed a lot of parameters, and the interaction between them are sometimes tricky to track/trace.
If you send me a small tile of your data (a portion of the plot that you think is representative of the whole plot) in any standard format (e.g. las), I can have a look and let you know what we see here.
If you think that's a good idea, please, send it to carloscabo@uniovi.es
Cheers.

**Comment by CaboCarlos** [comment]
Hi, Loris.
I had a quick look at the point cloud and it seems that the point density is very low: we have quite a lot of experience with Geoslam Horizon, and it seems like you have not exported 100% of the points. Changing the parameters in 3DFin makes feasible having some kind of 'decent' results anyway, but I'd check the density/decimation when exporting from the Geoslam Software.
If you want, you can send me another file with the full-resolution file and I can check again. Nevertheless, if you still want to use this point cloud as it is now, you'll have to change a lot of parameters, e.g. cloth resolution to 0.4m, voxelizations to 0.035-0.04m, number of points to 100-200, minimum number of points within each section to 30-40, section width for comuting diameters to 10-12cm, etc.. and play with them..
I hope this answer helps ;)

**Comment by Loris-L** [comment]
Thank you @CaboCarlos . That is a scan of last May, and we used a try license (2 weeks) of GeoSLAM software to only export the points clouds (we had done some scans). That was our first experience with GeoSLAM Zeb Horizon, and now we pay for this, because we didn't know about the possibility to check the density/decimation option, and now i (we) can't export it anymore from GeoSLAM software. From the next time we'll treasure your advices.

**Comment by CaboCarlos** [comment]
Loris:
If you still have the raw files from the scan, you can export them again. For instance, if you rented the device, most rental providers are happy to provide a license for acouple of days for subsequent processing. Also, maybe, it could be worth checking if the providers/owners of the scanner still have a copy of the raw data. I'm sayng all this because it is a pity to loose such a valuable dataset... 
Anyway, if none of the above are possible, let us know and maybe we can give a hand trying to find the right parameters toesctract some info with 3DFin..
Good luck!

**Comment by Loris-L** [comment]
@CaboCarlos thanks for your help and your tips, i'll personally recontacted you if there will be other problems. I tried to use the parameters that you suggested to me, and something is extracted. In the worst case, we'll redefine that parameters.
I close the issue, thanks also to @Diegolainor and @rjanvier (if you help me with the other problem about rendering on linux, i'll appreciate and i'll thank you further).

**Comment by CaboCarlos** [comment]
Sorry, Mattia, I've just seen your comment.
Sure! Count on our support!
Cheers
